### PR TITLE
Support custom prop types

### PR DESCRIPTION
**Pull request by jchavarri**
This is an exploration to support custom types (with custom sidebar controls as well) for demos / showcases.

It builds on top of `React.useState` to simplify the handling of props for each "demo unit", and introduces a continuation-based API for flexibility, e.g.

```reason
demo("Button", ({add}) =>
  add("normal", () =>
    boolProp("disabled", false, disabled =>
      stringProp("text", "hello", text =>
        [<button disabled> text->React.string </button>]
      )
    )
  )
);
```

The idea is that at the end, users return a list with one single element (the one they want to render in the main panel), and as the `*Prop` function calls return, they push the elements that will be showing on the sidebar. For example, in the case above the full list would be
```reason
[boolSidebarElement, stringSidebarElement, <button disabled>...</button>]
```

Supporting custom types is quite straight forward:

```reason
let dateProp =
  withControl((_date, setState) =>
    <button onClick={_event => setState(Js.Date.make())}>
      "Set to now"->React.string
    </button>
  );
```

and then:

```reason
demo("CustomProps", ({add}) =>
  add("now", () =>
    dateProp("date", Js.Date.make(), date =>
      [<h1> {date->Js.Date.toUTCString->React.string} </h1>]
    )
  )
);
```

I am convinced there are much better ways to type this 😅  Most probably @cristianoc and @wokalski have good insights, as this is quite similar somehow to the exploration that was done for hooks / slots in Brisk & Revery. I played a bit with [heterogeneous maps](https://github.com/dbuenzli/hmap/) and the heterogeneous list [in Brisk reconciler](https://github.com/briskml/brisk-reconciler/blob/master/lib/HeterogenousList.re) but the current approach with one list of elements seemed ultimately like a much simpler approach.

### CODE REVIEW

**Comment by wokalski** [comment]
@jchavarri it should be possible to create an api like this:
‘’’
add(“name”, [bool(“disabled”), string(“text”)], [disabled, text] => <button disabled> text->React.string </button> )
‘’’

**Comment by jchavarri** [comment]
@wokalski How would the props "control elements" be passed back so the library can render them with that kind of API?

This is the part that is challenging, and I think is similar to hooks: users need to be able to compose with custom types, that ultimately have to be "picked up" by the framework when the function calls return.

Like hooks, the proposed API could be made more ergonomic in the future with something like this? (like I believe Brisk hooks do?):

```reason
demo("Button", ({add}) =>
  add("normal", () =>
    let%boolProp disabled = ("disabled", false);
    let%stringProp text = ("text", "hello");
    (<button disabled> text->React.string </button>)->Entry.return
  )
);
```

**Comment by wokalski** [comment]
@jchavarri if we go down that route and you're into some type fiddling today, try it like so:

```
type prop('a) = {
  controlElement:
    (~children: React.element) => React.element,
  initialValue: 'a,
};

type hlist('a) =
  | []: hlist(unit)
  | ::(prop('a), hlist('l)): hlist('a => 'l);

module Props = {
  type t('a) =
    | []: t(unit)
    | ::(prop('a), t('l)): t('a => 'l);

  type opaqueProp =
    | Prop(prop('a)): opaqueProp;

  let rec map: type a. (~f: opaqueProp => 'b, t(a)) => list('b) =
    (~f, props) => {
      switch (props) {
      | [] => List.[]
      | [prop, ...rest] =>
        let hmap = map;
        List.[f(Prop(prop)), ...hmap(~f, rest)];
      };
    };
};

let add =
    (
      ~name as _: string,
      props: Props.t('a),
      render: hlist('a) => React.element,
    ) => {
  let controlElements =
    Props.map(
      ~f=
        (Props.Prop(prop)) => {
          let (value, set) = React.useState(() => prop.initialValue);
          (~children) =>
            prop.controlElement(
              ~set=value => set(_ => value),
              ~value,
              ~children,
            );
        },
      props,
    );
  ();
};
```

This is obviously not sufficient. The function from `Props.t('a) => hlist('a)` needs to be built. I think it's possible using [`constructor`](https://github.com/briskml/brisk-reconciler/blob/master/lib/HeterogenousList.rei#L18). You need to convert `Props.t('a)` into `hlist('a)` and into `list(element)` (or preferably `list((~children: React.element) => React.element)`).

---

That said, the API you've proposed is really easy to use with `ppx_let` 👍

**Comment by bloodyowl** [comment]
that'd be a really interesting feature. I tried to enable it before, but the old ReasonReact API didn't enable that. DX-wise I'd really like to extend the current API to add support for that, I wonder if we could enable custom props extensions through a functor: `Reshowcase.Make(MyCustomConfig)`

**Comment by jchavarri** [comment]
thanks @wokalski I will explore this a bit. My mind starts getting dizzy when I see things like `| ::(prop('a), hlist('l)): hlist('a => 'l);` though 😄 

@bloodyowl A functor-based approach can definitely work, but the main downside I see is that the functor should include all prop types from all demos in order to get a uniform type that can be passed down and stored in the maps, unless there is some type solution that allows each call to `demo` to get their own config? 🤔

**Pull request closed without merging**
